language: elixir
sudo: false
elixir:
  - 1.0.5
  - 1.1.1
  - 1.2.4
  - 1.3.2
otp_release:
  - 18.0
  - 18.1
  - 18.2
  - 18.3
  - 19.0
before_script:
  - kerl list installations
notifications:
  recipients:
    - igasgeek@me.com
matrix:
  exclude:
    - otp_release: 17.5
      elixir: 1.2.4
    - otp_release: 17.5
      elixir: 1.3.1
    - otp_release: 19.0
      elixir: 1.1.1
    - otp_release: 19.0
      elixir: 1.0.5
