language: elixir
sudo: false
elixir:
  - 1.3.4
  - 1.4.5
before_script:
  - kerl list installations
script:
  - mix test && mix credo --strict && mix dialyzer --halt-exit-status
notifications:
  recipients:
    - igasgeek@me.com
